services:
  admin-back-news-service:
    ports:
      - "8000:80"
    volumes:
      - ./admin-back-news-service:/var/www/html
    env_file:
      - ./admin-back-news-service/.env.dev


  admin-node-news-service:
    ports:
      - "8000:80"
    volumes:
      - ../node-admin-news-service:/var/www/html
    env_file:
      - ../node-admin-news-service/.env.dev
    command: npm run dev


  admin-front-news-service:
    ports:
      - "3000:3000"
    env_file:
      - ./admin-front-news-service/.env.dev
    volumes:
      - ./admin-front-news-service/src:/app/src
      - ./admin-front-news-service/public:/app/public
  # stdin_open: true