services:

  db:
    image: mysql:8.0
    container_name: prod-mysql
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - prod_db_data:/var/lib/mysql
    networks:
      - backend-network
  admin-node-news-service:
    image: paulodev183883/admin-news-back-node:latest
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      APP_ENV: production
      DEBUG: false
    # env_file:
    #   - ./admin-news-back-node/.env.prod
    mem_limit: 512m
    cpus: "0.50"
    restart: always


volumes:
  prod_db_data:

networks:
  backend-network:
    driver: bridge