services:

  admin-node-news-service:
    image: paulodev183883/admin-news-back-node:staging
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      APP_ENV: staging
    env_file:
      - ./admin-news-back-node/env.staging
    mem_limit: 512m
    cpus: "0.50"

    ## commentff  


